server:
  port: 9527
spring:
  application:
    name: mall-gateway #微服务名称
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: mall-consumer-feign #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9001   #匹配后提供服务的路由地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/consumer/goods/**,/consumer/order/**,/consumer/pay/**,/consumer/cart/** #路径断言，判断路径是否是以/consumer/login开头，如果是则符合

        - id: mall-seller-feign
          uri: http://localhost:9002
          predicates:
            - Path=/seller/goods/**,/seller/order/**

        - id: mall-seller-login
          uri: http://localhost:8501
          predicates:
            - Path=/seller/login/**


        - id: mall-consumer-login
          uri: http://localhost:8001
          predicates:
            - Path=/consumer/login/**

      #        - id: test
      #          uri: http://localhost:8501
      #          predicates:
      #            - Path=/test
      #          filters:
      #            #            - StripPrefix=1 #过滤器，去掉前缀，比如：/seller/login/1，去掉前缀后，请求的路径为/login/1
      #            - name: RequestRateLimiter #限流过滤器
      #              args:
      #                key-resolver: "#{@pathResolver}" #限流的key，这里使用IP地址作为限流的key
      #                redis-rate-limiter.replenishRate: 10 #令牌桶每秒新增的令牌数
      #                redis-rate-limiter.burstCapacity: 100 #令牌桶的容量
      #                redis-rate-limiter.enabled: true #是否启用限流
      #            - name: Hystrix #熔断过滤器
      #              args:
      #                name: fallbackcmd #熔断器的名称
      #                fallbackUri: forward:/fallback #熔断后的回调地址


      globalcors:
        cors-configurations: #跨域配置
          '[/**]':
            allowedOrigins: '*' #允许跨域的域名，可以用*表示允许任何域名使用
            allowedMethods: '*' #允许任何方法（post、get等）
            allowedHeaders: '*' #允许任何请求头
            allowCredentials: true #允许携带cookie
            maxAge: 18000 #预检请求的有效期，单位为秒
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST


# eureka 注册中心配置
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
