server:
  port: 8003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: mall-consumer-cart
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000


